---
scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000
  multiplier: 3

font:
  # Normal (roman) font face
  normal:
    family: Hack
    style: Regular
  size: 10.0

key_bindings:
  - key: Escape
    # NOTE: update to `Command` on MacOS
    mods: Super
    mode: ~Search
    action: ToggleViMode
