call_parentheses           = "Always"
collapse_simple_statement  = "Never"
column_width               = 80
indent_type                = "Spaces"
indent_width               = 4
quote_style                = "AutoPreferDouble"
space_after_function_names = "Never"

[sort_requires]
enabled = true
