"$schema" = "https://starship.rs/config-schema.json"

add_newline     = false
command_timeout = 2000
scan_timeout    = 50

[character]
error_symbol   = "[✗](bold red)"
success_symbol = "[❯](bold dimmed green)"
