require("lazy").setup({
	spec = {
		{ import = "plugins.colorschemes" },
		{ import = "plugins.core" },
		{ import = "plugins.ui" },
		{ import = "plugins.dependencies" },
		{ import = "plugins.lsp" },
		{ import = "plugins.formatting" },
		{ import = "plugins.debugging" },
		{ import = "plugins.git" },
		{ import = "plugins.dev" },
		{ import = "plugins.rust" },
		{ import = "plugins.go" },
		{ import = "plugins.python" },
		{ import = "plugins.testing" },
		{ import = "plugins.navigation" },
		{ import = "plugins.ai" },
		{ import = "plugins.linting" },
		{ import = "plugins.editors" },
		{ import = "plugins.editing" },
		{ import = "plugins.productivity" },
		{ import = "plugins.chezmoi" },
	},
	install = { colorscheme = { "onedark" } },
	checker = { enabled = true },
})
