set -as terminal-features ",xterm-256color:RGB"

bind r source-file ~/.config/tmux/tmux.conf

bind C-b last-window

# Avoid delay when hitting ESC in Vim.
set-option -s escape-time 10

set -g base-index 0

set-window-option -g mode-keys vi
set-option -g status-keys vi

# Use Vim keys for pane navigation and copy mode.
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

setw -g monitor-activity on
set -g visual-activity on
set -g aggressive-resize on

# Design
set -g set-titles on
set -g status-style fg=default,bg=black
set -g status-right-length 79
set -g status-justify left
set -g status-right '#[fg=magenta]#{user}#[fg=grey]@#[fg=green]#h #[fg=grey]%a %d %b %R'
set -g message-style fg=black,bg=brightmagenta,fill=brightmagenta
set -g pane-active-border-style fg=darkgreen
set -g pane-border-style fg=black
set -g window-status-style fg=grey,bg=default
set -g window-status-current-style fg=black,bg=brightred
set -g mode-style fg=black,bg=cyan
